default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: <%= ENV['postgres_username'] %>
  password: <%= ENV['postgres_password'] %>
  host: <%= ENV['postgres_host'] %>

development:
  <<: *default
  database: robot_world_development

test:
  <<: *default
  database: robot_world_test

production:
  <<: *default
  database: robot_world_production
